import type { ToolDefinition } from '../tool-definition.types';
import { CHATGPT_HANDLER_KEYS } from './chatgpt-handler.keys';

export const CHATGPT_STEP_PANEL_TOOLS: ToolDefinition[] = [
  {
    code: 'chatgpt_split_image',
    name: 'Cắt ảnh đôi',
    platform: 'chatgpt',
    handlerKey: CHATGPT_HANDLER_KEYS.splitImage,
    placement: 'step_panel',
    sortOrder: 0,
    defaultConfig: {},
    handlerScript: 'await host.captureAndSplitLatestImage();',
    guardScript: '!host.stepIsGenerateImages()',
    uiConfig: {
      displayGroup: 'image',
      displayOrder: 0,
      icon: 'scissors',
      copiedToolId: 'split-image',
      colSpan: 2,
      buttonClass: 'bg-blue-500/25 text-blue-100 hover:bg-blue-500/35',
      badgeClass: 'bg-blue-500',
    },
  },
  {
    code: 'chatgpt_copy_single_image',
    name: 'Sao chép ảnh',
    platform: 'chatgpt',
    handlerKey: CHATGPT_HANDLER_KEYS.copySingleImage,
    placement: 'step_panel',
    sortOrder: 5,
    defaultConfig: {},
    handlerScript: 'await host.copyLatestChatImage();',
    uiConfig: {
      displayGroup: 'image',
      displayOrder: 5,
      icon: 'image',
      copiedToolId: 'image-single',
      showCopyBadge: true,
      buttonClass: 'bg-cyan-500/25 text-cyan-100 hover:bg-cyan-500/35',
      badgeClass: 'bg-cyan-500',
    },
  },
  {
    code: 'chatgpt_copy_image_1',
    name: 'Sao chép ảnh 1',
    platform: 'chatgpt',
    handlerKey: CHATGPT_HANDLER_KEYS.copyImage,
    placement: 'step_panel',
    sortOrder: 10,
    defaultConfig: { part: 'left' },
    handlerScript:
      "const part = config.part === 'right' ? 'right' : 'left'; await host.copySplitImage(part);",
    guardScript: '!host.splitImages',
    uiConfig: {
      displayGroup: 'image',
      displayOrder: 10,
      icon: 'image',
      copiedToolId: 'image-left',
      showCopyBadge: true,
      buttonClass: 'bg-emerald-500/25 text-emerald-100 hover:bg-emerald-500/35',
      badgeClass: 'bg-emerald-500',
    },
  },
  {
    code: 'chatgpt_copy_image_2',
    name: 'Sao chép ảnh 2',
    platform: 'chatgpt',
    handlerKey: CHATGPT_HANDLER_KEYS.copyImage,
    placement: 'step_panel',
    sortOrder: 20,
    defaultConfig: { part: 'right' },
    handlerScript:
      "const part = config.part === 'right' ? 'right' : 'left'; await host.copySplitImage(part);",
    guardScript: '!host.splitImages',
    uiConfig: {
      displayGroup: 'image',
      displayOrder: 20,
      icon: 'image',
      copiedToolId: 'image-right',
      showCopyBadge: true,
      buttonClass: 'bg-emerald-500/25 text-emerald-100 hover:bg-emerald-500/35',
      badgeClass: 'bg-emerald-500',
    },
  },
  {
    code: 'chatgpt_copy_video_1',
    name: 'Copy VIDEO 1',
    platform: 'chatgpt',
    handlerKey: CHATGPT_HANDLER_KEYS.copyVideo,
    placement: 'step_panel',
    sortOrder: 30,
    defaultConfig: { part: 1 },
    handlerScript:
      'const part = config.part === 2 || config.part === "2" ? 2 : 1; await host.extractVideoContent(part);',
    guardScript: '!host.stepIsExtractVideos()',
    uiConfig: {
      displayGroup: 'video',
      displayOrder: 0,
      icon: 'film',
      copiedToolId: 'video-1',
      showCopyBadge: true,
      buttonClass: 'bg-blue-500/20 text-blue-100 hover:bg-blue-500/30',
      badgeClass: 'bg-blue-500',
    },
  },
  {
    code: 'chatgpt_copy_video_2',
    name: 'Copy VIDEO 2',
    platform: 'chatgpt',
    handlerKey: CHATGPT_HANDLER_KEYS.copyVideo,
    placement: 'step_panel',
    sortOrder: 40,
    defaultConfig: { part: 2 },
    handlerScript:
      'const part = config.part === 2 || config.part === "2" ? 2 : 1; await host.extractVideoContent(part);',
    guardScript: '!host.stepIsExtractVideos()',
    uiConfig: {
      displayGroup: 'video',
      displayOrder: 10,
      icon: 'film',
      copiedToolId: 'video-2',
      showCopyBadge: true,
      buttonClass: 'bg-blue-500/20 text-blue-100 hover:bg-blue-500/30',
      badgeClass: 'bg-blue-500',
    },
  },
  {
    code: 'chatgpt_copy_single_video',
    name: 'Lấy nội dung VIDEO',
    platform: 'chatgpt',
    handlerKey: CHATGPT_HANDLER_KEYS.copySingleVideo,
    placement: 'step_panel',
    sortOrder: 25,
    defaultConfig: {},
    handlerScript: 'await host.extractSingleVideoContent();',
    uiConfig: {
      displayGroup: 'video',
      displayOrder: 5,
      icon: 'film',
      copiedToolId: 'video-single',
      showCopyBadge: true,
      buttonClass: 'bg-indigo-500/25 text-indigo-100 hover:bg-indigo-500/35',
      badgeClass: 'bg-indigo-500',
    },
  },
  {
    code: 'chatgpt_copy_title_plain',
    name: 'Tiêu đề thường',
    platform: 'chatgpt',
    handlerKey: CHATGPT_HANDLER_KEYS.extractContent,
    placement: 'step_panel',
    sortOrder: 50,
    defaultConfig: { mode: 'title_plain' },
    handlerScript:
      "const mode = config.mode; if (mode === 'title_plain' || mode === 'title_styled' || mode === 'content_short' || mode === 'content_full') { await host.extractThreadContent(mode); }",
    guardScript: '!host.isExtractContentReady',
    uiConfig: {
      displayGroup: 'content',
      displayOrder: 0,
      icon: 'type',
      copiedToolId: 'step4-title_plain',
      showCopyBadge: true,
      buttonClass: 'bg-violet-500/20 text-violet-100 hover:bg-violet-500/30',
      badgeClass: 'bg-violet-600',
    },
  },
  {
    code: 'chatgpt_copy_title_styled',
    name: 'Tiêu đề font kiểu',
    platform: 'chatgpt',
    handlerKey: CHATGPT_HANDLER_KEYS.extractContent,
    placement: 'step_panel',
    sortOrder: 60,
    defaultConfig: { mode: 'title_styled' },
    handlerScript:
      "const mode = config.mode; if (mode === 'title_plain' || mode === 'title_styled' || mode === 'content_short' || mode === 'content_full') { await host.extractThreadContent(mode); }",
    guardScript: '!host.isExtractContentReady',
    uiConfig: {
      displayGroup: 'content',
      displayOrder: 10,
      icon: 'italic',
      copiedToolId: 'step4-title_styled',
      showCopyBadge: true,
      buttonClass: 'bg-violet-500/20 text-violet-100 hover:bg-violet-500/30',
      badgeClass: 'bg-violet-600',
    },
  },
  {
    code: 'chatgpt_copy_content_short',
    name: 'Nội dung ngắn',
    platform: 'chatgpt',
    handlerKey: CHATGPT_HANDLER_KEYS.extractContent,
    placement: 'step_panel',
    sortOrder: 70,
    defaultConfig: { mode: 'content_short' },
    handlerScript:
      "const mode = config.mode; if (mode === 'title_plain' || mode === 'title_styled' || mode === 'content_short' || mode === 'content_full') { await host.extractThreadContent(mode); }",
    guardScript: '!host.isExtractContentReady',
    uiConfig: {
      displayGroup: 'content',
      displayOrder: 20,
      icon: 'alignLeft',
      copiedToolId: 'step4-content_short',
      showCopyBadge: true,
      buttonClass: 'bg-amber-500/25 text-amber-100 hover:bg-amber-500/35',
      badgeClass: 'bg-amber-500',
    },
  },
  {
    code: 'chatgpt_copy_content_full',
    name: 'Nội dung đầy đủ',
    platform: 'chatgpt',
    handlerKey: CHATGPT_HANDLER_KEYS.extractContent,
    placement: 'step_panel',
    sortOrder: 80,
    defaultConfig: { mode: 'content_full' },
    handlerScript:
      "const mode = config.mode; if (mode === 'title_plain' || mode === 'title_styled' || mode === 'content_short' || mode === 'content_full') { await host.extractThreadContent(mode); }",
    guardScript: '!host.isExtractContentReady',
    uiConfig: {
      displayGroup: 'content',
      displayOrder: 30,
      icon: 'fileText',
      copiedToolId: 'step4-content_full',
      showCopyBadge: true,
      buttonClass: 'bg-pink-500/25 text-pink-100 hover:bg-pink-500/35',
      badgeClass: 'bg-pink-500',
    },
  },
];
